version: 0.0
phases:
    install:
        runtime-versions:
            java: corretto11
    pre_build:
        commands:
            - echo "Pre_build"
    build:
        commands:
            - echo "Build"
            - mvn clean install
            - aws s3 cp target/springboot-0.0.1-SNAPSHOT.war s3://lab11-codedeploy/
    post_build:
        commands:
            - echo "Post_build"
    artifacts:
        files:
            - target/*.war
            - scripts/server_start.sh
- scripts/server_stop.sh
- TestXMLFile.xml
- appspec.yml
